
# Language-related variables
MAJOR_TYPES := variable class superclass interface objectset structdef function
MINOR_TYPES := normal const system
DUMP_FILE   := lists/all.txt

# Build-related variables
OBJECTS     := $(sort $(foreach minor,$(MINOR_TYPES),$(addsuffix -$(minor),$(MAJOR_TYPES))))
OBJDIR      := lists/junk
OBJEXT      := .txt


# Binaries
EXTRACT     := utils/extract.js $(DUMP_FILE)


all: terms

.PHONY: clean graph


#==============================================================================

# Annihilate every file generated by build tasks
clean:
	@rm -rf $(OBJDIR)


# Print a decorated inheritance tree to illustrate MAXScript topology
graph:
	$(EXTRACT) --graph


# Build a list of all terms
terms: $(OBJDIR) $(OBJECTS:%=$(OBJDIR)/%$(OBJEXT))


#==============================================================================

# Create the objects directory if it's not been generated yet
$(OBJDIR):
	mkdir -p $@


# Build a single list of terms
$(OBJDIR)/%$(OBJEXT):
	$(EXTRACT) $(subst -, ,$(basename $(@F))) > $@
